### ISSUE TITLE
version 1.2.1 missing on grafana repository

### ISSUE THREAD

**Issue by babs** [LucasArona/larona-epict-panel#11]
Version 1.2.1 is not available on grafana repository, it stops at 1.2.0 :/

**Comment by LucasArona** [comment]
Yes, I [submitted](https://github.com/grafana/grafana-plugin-repository/pull/423) version 1.2.1 8 days ago to Grafana. Still waiting for approval.

**Comment by babs** [comment]
Oh it's a manual process on their side... Is there an easy way to manually install it ?

**Comment by LucasArona** [comment]
Yes, you can install it manually:

1) Backup
2) Download the latest version : https://github.com/LucasArona/larona-epict-panel/archive/master.zip
3) Unzip the files in your plugin directory (for example:` /var/lib/grafana/plugins`) so that the full path is `/var/lib/grafana/plugins/larona-epict-panel` (remove "-master" at the end of the folder)

that's the directory tree that you should have after
in `/var/lib/grafana/plugins/`
```
larona-epict-panel/
├── dist
│   ├── external
│   └── src
│       └── img
└── src
    ├── external
    └── img
```
and restart grafana service
`service grafana-server restart`

**Comment by babs** [comment]
I used git for the deploy but it works like a charm!
I can now have server room temps dashboard on the playlist displayed in the office :)

thanks :)
