### ISSUE TITLE
Cannot read property 'toFixed' of null

### ISSUE THREAD

**Issue by Azrael-Masters** [LucasArona/larona-epict-panel#3]
I've added a Image "http://192.168.0.51:3001/static/images/WP-Concept3.png" and added several Metrics & Boxes to it. It seems to be working and displaying the values.
But I get the following Errormessage:
![image](https://user-images.githubusercontent.com/10153187/51845713-585a2200-2318-11e9-941a-556bb8fb6600.png)

**Message:**
```
Cannot read property 'toFixed' of null
```

**Stack trace:**
```
TypeError: Cannot read property 'toFixed' of null
    at eval (http://192.168.0.51:3000/public/plugins/larona-epict-panel/epict_ctrl.js:114:113)
    at Array.forEach (<anonymous>)
    at EpictCtrl.onDataReceived (http://192.168.0.51:3000/public/plugins/larona-epict-panel/epict_ctrl.js:108:30)
    at s.emit (http://192.168.0.51:3000/public/build/vendor.469095018b321ef1da7c.js:86:11360)
    at t.emit (http://192.168.0.51:3000/public/build/app.469095018b321ef1da7c.js:1:181443)
    at EpictCtrl.e.handleQueryResult (http://192.168.0.51:3000/public/build/app.469095018b321ef1da7c.js:22:485994)
    at http://192.168.0.51:3000/public/build/vendor.469095018b321ef1da7c.js:130:92198
    at http://192.168.0.51:3000/public/build/vendor.469095018b321ef1da7c.js:130:92295
    at l.$digest (http://192.168.0.51:3000/public/build/vendor.469095018b321ef1da7c.js:130:97589)
    at l.$apply (http://192.168.0.51:3000/public/build/vendor.469095018b321ef1da7c.js:130:99592)
```

**Comment by Azrael-Masters** [comment]
Seems to happen if I'm working with Metric-Names with "Spaces" like "Aktuelle Verdichterfrequenz".
If I'm working with "A-series" it does seem to work.

**Comment by LucasArona** [comment]
Thanks for reporting this issue.
At the moment, I can't reproduce it.

Can you tell me what kind of Data Source you are using ?

**Comment by Azrael-Masters** [comment]
I'm using Google Chrome and InfluxDB Datasource, because the Data is coming from OpenHAB.
But now it seems also stopped working, because I can't see the Datavalues anymore.
Maybe it's my fault, but I don't see whats wrong.

![image](https://user-images.githubusercontent.com/10153187/51892269-abc48280-23a1-11e9-9ddd-a2fa912b9443.png)

**Querys:**
![image](https://user-images.githubusercontent.com/10153187/51892236-93ecfe80-23a1-11e9-96d5-a63c7a2b3e75.png)

**Options**
![image](https://user-images.githubusercontent.com/10153187/51892255-9ea79380-23a1-11e9-800b-8ee58ebbb403.png)

Same Metric in a Default-Chart seems to be working:
![image](https://user-images.githubusercontent.com/10153187/51892318-ceef3200-23a1-11e9-994e-728178ee7f2f.png)

**Comment by LucasArona** [comment]
Thanks for the screenshots and the details.
Here is what I found after doing some tests with the InfluxDB datasource:


If the field "Alias by" is empty (it's the case on your "Querys" screenshot), then, the name of the serie will be based on the name of the Measurement in InfluxDB.

Example for the query "A", the series name is:
**nibeUplink_Compressor_EB101EP14_CprFrequencyCurrent**.**mean**
So, that's what you have to use in the "Box definition" -> Metric Name (instead of "A-series")

However, if you write something in the "Alias by" field in the query definition, then you can use this alias in the Box definition -> Metric Name and it should work.

The problem here is that "A-series" is unknown since that's not the naming convention used by InfluxDB.

**Comment by Azrael-Masters** [comment]
Thanks a lot I tried both, which works and decided for the short Naming "A,B,C..." :).
But the strange JS Error is back :(
Any idea why?

![image](https://user-images.githubusercontent.com/10153187/51966369-9b2d0e80-246c-11e9-9cd9-e660ad76e010.png)

![image](https://user-images.githubusercontent.com/10153187/51966397-af710b80-246c-11e9-8e23-3534dce09f76.png)

**Comment by LucasArona** [comment]
Glad it's working again !

About the JS error, I did some tests: maybe, one of the series returns null values (because no data is available, for example).

Can you try this :
In the queries, replace the group by "Fill null" by "Fill 0". If the error disappears, I will update the code so that there is no need to do this in future versions

![image](https://user-images.githubusercontent.com/26776624/52083225-29091680-259f-11e9-8d1f-d1bbc39c88a8.png)

**Comment by Azrael-Masters** [comment]
I changed and will monitor it 👍

**Comment by Azrael-Masters** [comment]
Seems to be working without Issue 👍 

Thanks a lot for the fast und perfect help 🥇

**Comment by LucasArona** [comment]
Thanks for the feedback. The error message shouldn't show up anymore in a future release of the plugin.
