### ISSUE TITLE
link and treshold function don't work on grafana 8.0

### ISSUE THREAD

**Issue by elcaribou12** [LucasArona/larona-epict-panel#41]
Hello,

I try the plugin on grafana 8.00 and the link and treshold functions don't seems to work.

Did i miss something for the install ? Those functions previously work on grafana 7.5.5

Thanks in advance for your answer.

**Comment by LucasArona** [comment]
Hello,

I can't repro this issue, can you try with Grafana v8.0.1 and check that you are using the latest plugin version (2.0.3)?
What do you see when it's not working? The value is not showing at all?

Best regards,
Lucas

**Comment by elcaribou12** [comment]
Hi thank you for the rapid answer, i am on the 1.2.2 version of the plugin so i think it's the problem but now i don't know how to install the 2.0.3 because i'm on a docker install and the GF_INSTALL_PLUGINS	larona-epict-panel command install only 1.2.2...

**Comment by romalb47** [comment]
Hello,
I am a colleague of the person above. Grafan runs on the official docker version 8.0.0. When we try to install or list the versions we have no more recent than 1.2.2.

Regards,
Romain Albouy

`bash-5.1$ grafana-cli plugins install larona-epict-panel
✔ Downloaded larona-epict-panel v1.2.2 zip successfully

Please restart Grafana after installing plugins. Refer to Grafana documentation for instructions if necessary.

bash-5.1$ grafana-cli plugins list-versions larona-epict-panel
1.2.2
1.2.1
1.2.0
1.1.0
1.0.1
1.0.0
Please restart Grafana after installing plugins. Refer to Grafana documentation for instructions if necessary.`

**Comment by LucasArona** [comment]
Hello,

thanks for the details, I was able to repro the issue, I'll look into this!

In the meantime, you should be able to install the latest version with this command:
`grafana-cli --pluginUrl https://github.com/LucasArona/larona-epict-panel/releases/download/v2.0.3/larona-epict-panel-2.0.3.zip plugins install larona-epict-panel`

I'll let you know when the issue is fixed.

**Comment by elcaribou12** [comment]
Thank you very much for the help, this works for me, meanwhile i don't know why grafana cli take the 1.2.2 version of the plugin instead 2.03 which is signed !

**Comment by LucasArona** [comment]
The reason is that when I wrote version 2.0 of the plugin for Grafana v7, I added a dependency on Grafana `7.x.x` because the plugin was not compatible with Grafana v6.
However, I should've written `>=7.x.x` instead of `7.x.x` in plugin.json. So, yeah, that's a silly mistake... I'll release a new version of the plugin to fix this, then I'll send it to Grafana for approval.

**Comment by elcaribou12** [comment]
Ok perfect, thank you again for your quick response.

**Comment by LucasArona** [comment]
Version 2.0.4 is now published and visible with grafana-cli

```bash
~$ grafana-cli plugins list-versions larona-epict-panel
2.0.4
1.2.2
1.2.1
1.2.0
1.1.0
1.0.1
1.0.0
```
