### ISSUE TITLE
Refresh Background Image

### ISSUE THREAD

**Issue by laurafernandezdiaz** [LucasArona/larona-epict-panel#58]
I am using Grafana 8.2.1 version with this panel and it works perfectly, it is very useful for me. 

A use case that came to mind is to be able to refresh the image. We have an image that is updated (changing) in a path every 5s naming the image in the same way (replaces it). I have been testing with the plugin but I don't see a way to catch those changes beyond deleting the cache of each time or creating a new graph. How could it be done?

**Comment by LucasArona** [comment]
Thanks for your feedback!

To force the browser to refresh the image, you can try to add a parameter that changes regularly, somewhere in the URL. This will prevent caching.

Such as: `$__from` (or `$__to`), because Grafana replaces the `$__from` variable by the start time of the interval used in your dashboard, each time the dashboard is refreshed.
This will only work if your dashboard uses an absolute time range (such as `Last 15 minutes`). The `$__from` value is always updated when your dashboard is refreshed.
Then, you can enable auto-refresh on your dashboard in order to avoid refreshing the dashboard manually.

**Example:**
If the URL of your image is currently: `https://webserver/picture.jpg`
Try to use something like this instead: `https://webserver/picture.jpg?timestamp=$__from`

The `timestamp` parameter can be whatever you want as long as the server hosting your image doesn't process it, the goal is to "trick" the browser and prevent caching. Without a "dynamic" parameter such as `$__from`, the browser detects the URL is always the same and will not download the image again.


If you want to learn more about global variables in Grafana: https://grafana.com/docs/grafana/latest/variables/variable-types/global-variables/

Let me know if this works for you or if you need further assistance.

**Comment by laurafernandezdiaz** [comment]
Thank you very much it works perfectly :)

In this way the image is updated as indicated in auto refresh.
