### ISSUE TITLE
Scalable and transparent image

### ISSUE THREAD

**Issue by code4me-xx** [LucasArona/larona-epict-panel#9]
Really nice add on for Grafana!

Is it possible to make the selected image scale with the Grafana panel and honor transparency?

Right now the size seams to be fixed and won't scale with the panel. I've tried to use a .png with transparency but can't make that work either.

Regards Peter

**Comment by LucasArona** [comment]
Thanks for the feedback Peter !

About the transparency:
Can you tell me the Grafana version, and which browser you are using ?
I tested with a transparent PNG and it worked:

![image](https://user-images.githubusercontent.com/26776624/56160098-8f121100-5fc6-11e9-8800-7c8be45ee8ce.png)

The image I used for the test is the one provided here: https://www.w3.org/Graphics/PNG/inline-alpha.html -> https://www.w3.org/Graphics/PNG/alphatest.png

Can you try with this one too ?


About the sizing: I think that the image should not resize, otherwise the metrics will not be aligned anymore (unless we adjust the font-size as the image is scaled down or up, and it will be quite hard to guarantee that the items stay aligned), do you have a suggestion or an idea about how should it behave when the size is modified ?

**Comment by code4me-xx** [comment]
Hi Lucas,

You were right about transparency it is working there was an error in my file.

I think sizing is important when using view mode on panels, for cross platform solutions (Resolution), different resolutions and when resizing. It could be an option and the metrics position should follow the scale just like positions on a map, but I don't think the size needs to.

A temporary solution for the metrics could be to save the image with annotations (A, B, C)  and then just list the metrics like a legend.

Regards Peter

**Comment by jpmeijers** [comment]
I think it will be very useful if the image can scale by panel size. This will allow this plugin to work on mobile devices and smaller screens, and will allow one to use any size source image and make it fit the panel's current size.

1. When drawing the image, fit to panel keeping aspect ration. Save scaling factor.
2. Use scaling factor to scale x and y coordinates.
3. Use scaling factor to scale font dpi.

**Comment by LucasArona** [comment]
Thank you for your input. I'll do some tests regarding the scaling.

**Comment by balpak** [comment]
Hi Lucas,
If you plan to continue work on scaling could you please make this feature "optional"? Would be nice if user could switch it on/off instead of automatic scaling. 

I've tried https://grafana.com/grafana/plugins/pierosavi-imageit-panel which has scaling feature by default and do not like how it works.

Thanks,
Yuri

**Comment by LucasArona** [comment]
Hello,
yes, I agree, that definitely has to be an option !

**Comment by mirkocomparetti-synesis** [comment]
Hello @LucasArona,
Any news on the scaling? I'm trying out the panel but the image is too big and I can't use it :(

Thanks!
